export const pageStyles = {
  page: {
    padding: '32px',
    background: '#f1f5f9',
    minHeight: '100vh',
    fontFamily: "'Segoe UI', sans-serif",
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 24,
  },
  title: {
    fontSize: 26,
    fontWeight: 700,
    color: '#0f172a',
    margin: '0 0 4px',
  },
  sub: {
    color: '#64748b',
    fontSize: 13,
    margin: 0,
  },
  btnPrimary: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 18px',
    background: '#16a34a',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
  },
  btnSecondary: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 18px',
    background: '#fff',
    color: '#374151',
    border: '1.5px solid #e2e8f0',
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 500,
    cursor: 'pointer',
  },
  btnDanger: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 18px',
    background: '#fff',
    color: '#dc2626',
    border: '1.5px solid #fecaca',
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 500,
    cursor: 'pointer',
  },
  searchWrap: {
    position: 'relative',
    marginBottom: 16,
  },
  searchIcon: {
    position: 'absolute',
    left: 12,
    top: '50%',
    transform: 'translateY(-50%)',
    color: '#94a3b8',
    pointerEvents: 'none',
  },
  searchInput: {
    width: '100%',
    padding: '10px 12px 10px 38px',
    border: '1.5px solid #e2e8f0',
    borderRadius: 8,
    fontSize: 14,
    background: '#fff',
    outline: 'none',
    boxSizing: 'border-box',
    color: '#374151',
  },
  tableCard: {
    background: '#fff',
    borderRadius: 12,
    border: '1px solid #f1f5f9',
    boxShadow: '0 1px 3px rgba(0,0,0,0.07)',
    overflow: 'hidden',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: 14,
  },
  th: {
    padding: '12px 16px',
    textAlign: 'left',
    color: '#94a3b8',
    fontWeight: 500,
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    background: '#f8fafc',
    borderBottom: '1px solid #f1f5f9',
  },
  td: {
    padding: '13px 16px',
    color: '#374151',
    borderBottom: '1px solid #f8fafc',
    verticalAlign: 'middle',
  },
  tr: {
    cursor: 'pointer',
    transition: 'background 0.12s',
  },
  mono: {
    fontFamily: 'monospace',
    fontSize: 12,
    background: '#f1f5f9',
    padding: '2px 7px',
    borderRadius: 4,
    color: '#475569',
  },
  badgeSuccess: {
    background: '#dcfce7',
    color: '#16a34a',
    fontSize: 12,
    fontWeight: 600,
    padding: '3px 10px',
    borderRadius: 20,
    whiteSpace: 'nowrap',
  },
  badgeDanger: {
    background: '#fee2e2',
    color: '#dc2626',
    fontSize: 12,
    fontWeight: 600,
    padding: '3px 10px',
    borderRadius: 20,
    whiteSpace: 'nowrap',
  },
  badgeWarning: {
    background: '#fef3c7',
    color: '#d97706',
    fontSize: 12,
    fontWeight: 600,
    padding: '3px 10px',
    borderRadius: 20,
    whiteSpace: 'nowrap',
  },
  badgeBlue: {
    background: '#dbeafe',
    color: '#2563eb',
    fontSize: 12,
    fontWeight: 600,
    padding: '3px 10px',
    borderRadius: 20,
    whiteSpace: 'nowrap',
  },
  badgeNeutral: {
    background: '#f1f5f9',
    color: '#475569',
    fontSize: 12,
    fontWeight: 500,
    padding: '3px 10px',
    borderRadius: 20,
    whiteSpace: 'nowrap',
  },
};
